import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-primary px-10 lg:px-60 md:px-30">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
